feat: add workflow to deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -59,29 +59,37 @@ jobs:
 
       - name: Replace Terraform placeholders
         run: |
+            set -e
+
             export LC_ALL=en_US.UTF-8
             export LANG=en_US.UTF-8
 
-            TF_OUTPUT_JSON=$(cat terraform/envs/dev/tf_outputs.json)
+            TF_FILE="terraform/envs/dev/tf_outputs.json"
 
-            Terraform Outputs =$($TF_OUTPUT_JSON" | jq ...)
+            echo "Using Terraform outputs from: $TF_FILE"
+            jq '.' "$TF_FILE" >/dev/null   # sanity check (will fail if JSON is broken)
 
-            echo "Terraform Outputs: $TF_OUTPUT_JSON"
-
-            # Loop over all keys
-            for key in $(echo "$TF_OUTPUT_JSON" | jq -r 'keys[]'); do
-            # Get the value safely as JSON string
-            value=$(echo "$TF_OUTPUT_JSON" | jq -r ".\"$key\".value | @json")
-            # Remove surrounding quotes if it's a string
-            value=$(echo "$value" | sed 's/^"\(.*\)"$/\1/')
+            # Loop over all Terraform outputs
+            jq -r 'keys[]' "$TF_FILE" | while read -r key; do
+            value=$(jq -r ".\"$key\".value" "$TF_FILE")
 
             echo "Replacing placeholder \${$key} with $value"
 
             # Replace in ansible directory
-            find ansible -type f ! -name "*.png" ! -name "*.jpg" ! -name "*.zip" ! -path "./terraform/*" -exec sed -i.bak "s|\${$key}|$value|g" {} \; -exec rm -f {}.bak \;
+            find ansible \
+                -type f \
+                ! -path "./terraform/*" \
+                ! -name "*.png" ! -name "*.jpg" ! -name "*.zip" \
+                -exec sed -i.bak "s|\${$key}|$value|g" {} \; \
+                -exec rm -f {}.bak \;
 
             # Replace in application directory
-            find application -type f ! -name "*.png" ! -name "*.jpg" ! -name "*.zip" ! -path "./terraform/*" -exec sed -i.bak "s|\${$key}|$value|g" {} \; -exec rm -f {}.bak \;
+            find application \
+                -type f \
+                ! -path "./terraform/*" \
+                ! -name "*.png" ! -name "*.jpg" ! -name "*.zip" \
+                -exec sed -i.bak "s|\${$key}|$value|g" {} \; \
+                -exec rm -f {}.bak \;
             done
 
       - name: Install Ansible
